### ISSUE TITLE
Error give keys

### ISSUE THREAD

**Issue by xChristianTWM** [Katania91/kt-deliveries#1]
Hello!!

On line 247, the Config.Framework was being compared to 'qb-core' when it should be 'qbcore' (due to how it is placed by default in the config file) so it was not handing the keys to the vehicle.

Original:
```lua
if Config.Framework == "qb-core" then TriggerServerEvent('qb-vehiclekeys:server:AcquireVehicleKeys', string.gsub(GetVehicleNumberPlateText(furgone), '^%s*(.-)%s*$', '%1'), true) end -- for qb only
```

Fixed:
```lua
if Config.Framework == "qbcore" then TriggerServerEvent('qb-vehiclekeys:server:AcquireVehicleKeys', string.gsub(GetVehicleNumberPlateText(furgone), '^%s*(.-)%s*$', '%1'), true) end -- for qb only
```

**Comment by Katania91** [comment]
Hello,

Thanks for your message, I'll do a fix tonight!

Katania

Il Lun 18 Nov 2024, 18:35 xChristianTWM ***@***.***> ha
scritto:
